const express = require('express')
const dotenv = require('dotenv')
const cors = require('cors')
const userRouter = require('./routes/user.route')
const authRouter = require('./routes/auth.route')
dotenv.config()
const app = express()
app.use(express.json())
app.use(cors())
app.get("/healthy", (req, res) => {
  res.status(200).send("Server is healthy")
})
app.use('/api/user', userRouter)
app.use('/api/auth', authRouter)
module.exports = app